### ISSUE TITLE
massively reduce or eliminate shout move cost

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#131]
There's always griefers but people likely to log into sneezymud these days are unlikely to both shout too much and not qualify for a blanket ban. Especially since we have the cost-free newbie channel now.

**Comment by Aion2501** [comment]
I vote to leave in SOME movement cost to shouting, simply because it makes sense. Perhaps 15mv instead of 30. However, there are also many games that have an anti-spam timer to prevent people from using any global channel too often. 

A common example is more than 1 broadcast per second nulls the second message, mutes the player for 5 seconds, and returns a message to the spammy player. "You need to wait a moment before sending more messages." 
More than 2 broadcasts in 10 seconds mutes them for 30 seconds. 
And then of course a report function; highlighting a specific offensive broadcast from a player and notifying admins.

**Comment by rmsr** [comment]
Trolly shouting players is sometimes a nice problem to have!

Maybe it shout use a percentage of your move rather than a flat amount. IDK what the default move regen rate is though. In any case, you should be able to carry on a comfortable extended conversation at a reasonable pace.

**Comment by Leyline77** [comment]
It's a silly restriction from the times when it was expensive CPU costs for the mud to handle, but even since 1992 there's always been an alternative / cost free global message workaround.  Just make it normal and free.  There's always #ignore for spam. (zMud forever!)

**Comment by cizra** [comment]
Disagreed about the restriction — Sneezy wastes CPU left and right (just imagine every trash collector breadth-first searching half the MUD for trash). Pumping a line of data across is neglible, and we do it all the time anyway — that's what a MUD is for.

I'm certain the reason used to be spam. I'm all for reducing the cost of communication.

**Comment by Aion2501** [comment]
I've updated this and submitted a pull request. Shout will now cost 15mv down from 30mv.
