### ISSUE TITLE
trip: give thieves the trip skill

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#161]
Thieves lack a (low-level) interrupt skill. Give them one, in the base thief discipline.

**Comment by drewhershey** [comment]
This is something I've thought about quite a few times before while playing so I thought I'd chime in with some ideas.

I always assumed the reasoning for warriors getting the trip skill was to allow lower level players an equivalent of bash if not using a shield, or in situations where size differences made bash unavailable.

Looking quickly, here's the main ways bash and trip differ: 

**Hard Failures (prevent from even attempting)**
- Bash unavailable if attacker is more than 3x taller than victim; Trip doesn't care if attacker is taller, except it's unavailable against victims less than 12 units tall.

- Bash unavailable if attacker is shorter than 2/3 victim's height; Trip unavailable if attacker is shorter than 1/3 victim's height. 

- Bash unavailable without a shield in offhand until warrior has at least 10% in the brawling advanced disc. Trip has no such limitation.

- Bash is possible if both parties are flying, but not if only one is. Trip is only possible if both parties are on the ground, standing.

**Skill Success Chance Modifiers**
- In a multi-person fight, bash gets a flat -35% penalty to bSuccess check if attacker isn't also the tank. Trip gets no such penalty.

- Weight of attacker vs weight of defender is factored into the bSuccess check for both bash and trip, so lighter characters are at a disadvantage either way.

- Bash gets a bonus to bSuccess check depending on either the weight of the attacker's shield or, if not using a shield, their skill in the brawling discipline. Trip gets no bonuses to success from anything.

My initial instinct for changes is:
1) Make bash usable with either a shield or a two-handed weapon from the beginning
2) Tweak it to favor stronger and/or brawnier and/or heavier characters somehow
3) Apply the existing bonus to success from shield weight to two-handed weapon weight as well
4) Keep it so that having the brawling disc allows bashing while bare-handed or dual-wielding
5) Move trip to the thief class as suggested and remove it from warrior
6) Tweak trip to favor lighter and/or more dexterous characters, as a successful trip is much more about timing and leverage than brute force.
7) Remove the height restrictions on both skills, or at least factor them into the bSuccess checks instead of just using them as scenarios for outright failure. (A short, powerful dwarf could still bash a tall, gangly gnoll and a tiny, dexterous hobbit should be able to stick a foot or weapon out at just the right time to trip up a tall, strong ogre.)

**Comment by drewhershey** [comment]
Whoops... clicked the wrong button.

**Comment by rmsr** [comment]
That's a great analysis! I really appreciate you comparing bash to trip like this.

I think regular bashing requiring a shield makes sense. I don't know what about a 2h weapon would make it suitable for bashing people - I think the brawl-bash is a shoulder shove vs anything involving held items. I also think that when you're flying, bashing a grounded target should be *easier* not impossible. The hard height cutoffs are silly yes. TIckets opened #168 #169

I don't know about the smaller tweaks vs weight for each skill, that's something we could look into when we have a versatile combat simulator or good fight logger to peruse for statistical information, and can make informed decisions about it.

The easiest fix for this is to just give thieves trip and not take it from warriors, because after reading this, given the relative limitations of bash vs trip, I think warriors should have it still. Updating the ticket to reflect that.

**Comment by wershlak** [comment]
@drewhershey Review your notes here. I'm going to close this out specific issue in light of some of the wider ranging changes you have planned for thieves.
