### ISSUE TITLE
noop shouldn't interrupt meditation

### ISSUE THREAD

**Issue by wershlak** [sneezymud/sneezymud#316]
```
H:490 M:218 P:100.0 V:130 R:9503 > med
You rest and begin to meditate.


MANA : 218 > H:490 M:218 P:100.0 V:130 R:9503 > noop
Your meditation has slightly increased your sense of well being!


MANA : 219 > H:491 M:219 P:100.0 V:130 R:9503 >
You break your focus...
```

**Comment by Hordeking** [comment]
noop doesn't actually do anything but return true from the parser. Whatever the check for broken focus is happening before it gets to where noop is evaluated.

If I remember right, lots of meta commands also have issues like this, for instance, being asleep will prevent you from reading help files and so on.

Perhaps we can add an attribute to our verbs that can be checked for meta status, so that they don't actually affect the game state? Or we simply check for these at an earlier stage and return before executing other checks like if the player is meditating?

**Comment by wershlak** [comment]
The command array specifies when you can do a command by your position. This would keep you from dancing when you are sitting down or using help when asleep. Pretty easy to adjust these if we feel like they are annoying or unrealistic restrictions.
https://github.com/sneezymud/sneezymud/blob/master/code/code/misc/parse.cc#L2439

But in true sneezy form we've built checks for other things elsewhere rather than expanding commandInfo. 

Hide: https://github.com/sneezymud/sneezymud/blob/master/code/code/misc/parse.cc#L102
Tasks: https://github.com/sneezymud/sneezymud/blob/master/code/code/misc/task.cc#L239-L309
Casting: https://github.com/sneezymud/sneezymud/blob/master/code/code/misc/spelltask.cc#L2898-L2936

Seems like cmd_nop needs to be included in these spots as well.

**Comment by cizra** [comment]
I never understood why you need to have the noop command anyway. Sending an empty line would do the same as noop currently does. If your client cannot send an empty line, it's a client issue.
