### ISSUE TITLE
Mage Spell: Gate

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#69]
I'd like to see a little overlap with classes. First concept:

**Gate:** A spell that functions very similarly to Portal.

Loose on the details. Maybe just the same functionality but requiring a new component item. Keep it simple for now.  The best place I can imagine it going right now is deep in the Water Magic tree.

**Comment by nenbeely** [comment]
What about overlap using an existing spell but tweaking it - I'm thinking of Knot. Right now it's a solo transport to the Knot, but we could have it instead open the rip in spacetime such that an entire party could walk through. 

 Could be an interesting difference, where clerics can use the hand of their god to directly go where they want, versus mages can steer folks into this chaotic dimension - but it has some advantages, since the Knot can lead to zones that aren't normally astral-able.

**Comment by sntwo** [comment]
I'd agree with nenbeely in that keeping class specialties unique to their class is a good thing.  I haven't figured out a lot about the knot yet but expanding that capability seems like the best way to buff mages utility to be more equal with clerics.  Also regarding mage utility, I think eyes of fertuman should be restored to it's old locate object power.

That said, one issue the mud is facing right now is deciding what changes should occur and making those changes.  We have some willing coders (and wannabe coders like me :P) but I don't feel like implementing things that affect the balance of the game is within my purview, even though many of the issues posted here lately seem doable.  Hence my immediate focus has been on trying to provide systems that make it easier for the game admin to change things.

**Comment by wershlak** [comment]
This is resolved
