### ISSUE TITLE
Add command to completely dump and zip pfiles from within game

### ISSUE THREAD

**Issue by Hordeking** [sneezymud/sneezymud#93]
This probably already exists, but I'm putting it here as a reminder. I only know how to dump these from outside of the mud, and that has potential issues.

**Comment by rmsr** [comment]
pfiles are kept up to date basically in realtime, so there's no "dumping" needed. if you need a consistent global snapshot of the pfiles and whatever else, just hit sneezy it with SIGSTOP, do your thang, and then SIGCONT when you're done.

in any case, since we're going to eliminate pfiles entirely, I'm not sure pfile-related features are useful. what specifically do you intend to do with the pfiles after they are zipped? just backups?

**Comment by rmsr** [comment]
given that we've moved up the schedule for eliminating pfiles, closing this.
